config/routes.rb
Newtone::Application.routes.draw do
  root :to => "recognition#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/about' => 'home#about'

  scope :recognition do
    get '/file' => 'recognition#file', :as => :recognize_file
    get '/record' => 'recognition#record', :as => :recognize_record
    post '/recognize' => 'recognition#recognize', :as => :recognize
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/track.rb
class Track < ActiveRecord::Base
  include Noisia::Track
  #validates :author, :name, :fingerprint, :presence => true
  mount_uploader :file, TrackUploader

  def update_fingerprint
    self.fingerprint = Fingerprint.new(file.file.file).build
  end

  def self.seed
    songs = ['Без шансов', 'Гора', 'Деньги', 'Если бы', 'Кофевино', 'Похоронила', 'Река', 'Чайка', 'Жить В Твоей Голове', 'Кувырок']
    songs.map do |song|
      my_file = "/Users/unloved/Downloads/Земфира - #{song}.mp3"
      t=Track.new(:name=>song, :author=>'Земфира')
      t.file.store!(File.open(my_file))
      t.save
    end
  end

  def self.reseed
    Noisia::Elastic.recreate_index
    self.destroy_all
    self.seed
  end

  def generate_fingerprint
    self.fingerprint = Noisia::Fingerprint.new(file.path, :add, default_density).build
  end

  def force_store_elastic
    generate_fingerprint
    Noisia::Elastic.store_track(self)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates_presence_of :name

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end
end

app/controllers/recognition_controller.rb
class RecognitionController < ApplicationController

  def index

  end

  def file

  end

  def record

  end

  def recognize
    audio_path = params[:audio][:sample].tempfile.path
    file_ext = params[:audio][:sample].original_filename.split('.').last
    new_path = "#{Rails.root}/tmp/upload_tracks/#{Time.now.to_i.to_s}-#{rand(999999)}.#{file_ext}"
    FileUtils.cp(audio_path, new_path)
    puts 'start recogn'
    result = Recognition.new(new_path).results
    FileUtils.rm(new_path)
    render :json => result
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    user.add_role :admin if User.count == 1 # make the first user an admin
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fontello icon, custom_class = ''
    #icon = case icon
    #  when 'wants' || 'want' || 'get' || 'wanted_items' then 'star'
    #  else icon
    #end
    content_tag :i, '', :class => "fontello-icon-#{icon} #{custom_class}"
  end

end

app/helpers/buttons_helper.rb
module ButtonsHelper
  def select_audio_source_button type, url=nil
    case type
      when :record
        icon = 'mic'
        tooltip_text = I18n.t('audio_sources.recognize_record')
      when :file
        icon = 'upload'
        tooltip_text = I18n.t('audio_sources.recognize_file')
    end
    button = content_tag(:div, "#{fontello(icon, 'select-audio-button-icon')}".html_safe, :class => 'select-audio-source-button-link')
    tooltip = content_tag(:div, tooltip_text, :class => 'select-audio-source-button-caption')
    active_link_to( "#{button} #{tooltip}".html_safe, url)
  end

  def new_recognition_button
    button = content_tag(:div, "#{fontello('cw', 'select-audio-button-icon')}".html_safe, :class => 'select-audio-source-button-link')
    tooltip = content_tag(:div, I18n.t('recognize_new_track'), :class => 'select-audio-source-button-caption')
    active_link_to( "#{button} #{tooltip}".html_safe, 'javascript:showAudioSourceBlock()', :id=>:new_recognition)
  end
end

app/views/home/about.html.haml
Этот проект вам не хухры мухры

app/views/layouts/_1navigation.html.erb
<%= link_to "Newtone", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_footer.html.haml
.row
  .col-md-3
    .pull-left= image_tag image_path('logo.png')
    %h4.no-margins.brandname.pull-left Newtone
  .col-md-2.col-md-offset-7
    = link_to 'http://brandymint.ru/' do
      = image_tag image_path('brandymint.png')

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.erb
<%= link_to "Newtone", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_navigation.html.haml
.navbar.navbar-static-top.navbar-inverse{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Newtone', root_url, :class => 'navbar-brand'
    .collapse.navbar-collapse
      = render_navigation :expand_all => true, :renderer => :bootstrap

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Newtone"
    %meta{:content => content_for?(:description) ? yield(:description) : "Newtone", :name => "description"}
    %link{:rel=>'image_src', :href=>image_path('newtone-caption.png')}
    = favicon_link_tag image_path('favicon.ico')
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'layouts/navigation'
    .container
      .row
        .col-md-12
          = render 'layouts/messages'
          = yield
      -#.footer
      -#  = render 'layouts/footer'

app/views/recognition/_recognition.html.haml
.row
  .col-md-6
    .j.newtone-face.newtone-normal
    - [:bad, :good].each do |state|
      .j.newtone-face.hidden{:class => "newtone-#{state}"}
  .col-md-6
    .recognition-container
      .audio-source-block
        %h1.newtone-speach.pull-left
          = t('newtone_speach.welcome').html_safe
        .clearfix
        .row.select-audio-source
          .col-md-1
          .col-md-5
            = select_audio_source_button :record, url_for(:recognize_record)
          .col-md-5
            = select_audio_source_button :file, url_for(:recognize_file)
          .col-md-1
        = yield :recognition_type_body
      .clearfix

      .processing-block.spinner-block
        %h1.newtone-speach.pull-left
          = t('newtone_speach.processing').html_safe
        .pull-right
          %a#cancel_processing{"data-original-title" => I18n.t('cancel_processing'), href: "javascript:void(0)", rel: "tooltip"}
            %i.fontello-icon-cancel-circled.icon-size-24
        .clearfix
        .center-block
          .ui-spinner
            %span.side.side-left
              %span.fill
            %span.side.side-right
              %span.fill
        .clearfix

      .results-block
        .bad
          %h1.newtone-speach.pull-left
            = t('newtone_speach.results.bad').html_safe
          .clearfix
          .row
            .col-md-9
              .text
              = t('newtone_speach.results.bad_text').html_safe
            .col-md-3
              = new_recognition_button
        .good
          %h1.newtone-speach.pull-left
            = t('newtone_speach.results.good').html_safe
          .clearfix
          .row
            .col-md-9
              .text
                .result
                  Artist - Song

            .col-md-3
              = new_recognition_button
        .clearfix

      .error-block
        %h1.newtone-speach.pull-left
          = t('newtone_speach.error').html_safe
        .row
          %p.font-weight-normal.text
            = t('error').html_safe
        %hr.small
        %h3.font-weight-normal
          = link_to "#{fontello('left-circled', 24)} #{t('go_back')}".html_safe, "javascript:history.go(0)"
        .clearfix

app/views/recognition/file.html.haml
- content_for :recognition_type_body do
  .audio-source-block-file
    %button#select.btn.btn-large.btn-success
      = t('audio_sources.upload.select')
    %button#submit.btn.btn-large.btn-primary.disabled
      = t('audio_sources.upload.submit')
    = file_field :audio, :sample, :class => 'audio-upload-input', :data => {:url => recognize_path}
    -#.browse-button
    -#        = button_tag t('audio_sources.upload.select'), :class => 'btn btn-large btn-primary select-button'
    -#        = file_field :audio, :sample, :class => 'audio-upload-input', :data => {:url => recognize_path}
    -#      .clearfix
    -#      %br
    -#      = link_to t('audio_sources.upload.submit'), "javascript:void(0);", :class => 'btn btn-large btn-primary upload-button disabled'


= render 'recognition'

app/views/recognition/index.html.haml
- content_for :recognition_type_body do
  выберите один из аудио источников выше

= render 'recognition'

#recognition-container

app/views/recognition/record.html.haml
- content_for :recognition_type_body do
  .audio-source-block-record
    #flash-container
    %button#record.j.btn.btn-large.btn-success
      = t('audio_sources.record.record')
    %button#play.btn.btn-large.btn-primary.hidden
      = t('audio_sources.record.play')
    %button#stop.btn.btn-large.btn-danger.hidden
      = t('audio_sources.record.stop')
    %button#submit.btn.btn-large.btn-primary.disabled
      = t('audio_sources.record.submit')
= render 'recognition'

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}